### ISSUE TITLE
useMediaQuery - hydration mismatch: shouldn't it use useIsomorphicLayoutEffect ?

### ISSUE THREAD

**Issue by hepiyellow** [juliencrn/usehooks-ts#151]
The hook as it is right now is causing hydration mismatch.

If I change it to use `useIsomorphicLayoutEffect` (instead of `useEffect`),
the the hydration warning is gone, and it seems to work.

I don't fully understand yet what exactly is going on,
but could it be the proper solution?

**Comment by hepiyellow** [comment]
oops

**Comment by matewka** [comment]
In my case using this helped:
```
useMediaQuery('(min-width: 1024px)', {
  initializeWithValue: false
})
```

On the server, the query was automatically defaulting to `false`, while on the client it returned `true` because the browser's window width was above 1024px. Using `initializeWithValue: false` causes the hydration render to use `false` instead, which solves the hydration mismatch problem.
