### ISSUE TITLE
useLocalStorage() store the incorrect value

### ISSUE THREAD

**Issue by Chandler-Zhu** [juliencrn/usehooks-ts#170]
I was using a component library with [usehook-ts](https://usehooks-ts.com/react-hook/use-local-storage), and I want to save the user's rating in localStorage so next time they visit the same page they can see the rating. Now the current behavior I am getting is after user interact with the rating component, when they come back again or simply refresh the value is always 5 out of 5 no matter what their input was.
The component I am using: https://shoelace.style/components/rating
repro: https://codesandbox.io/s/solitary-pine-hjgqbg?file=/pages/index.js

**Comment by juliencrn** [comment]
Hi, I think the problem comes from the other lib or your implementation. I've added a `console.log(value)` in your `saveRating` function and I saw two things: 
- when you click on a star to rate, there is an infinite loop
- and the `value` isn't a number between 0 and 5 but a `CustomEvent` from the lib.

If you inspect localStorage, you can see that the `memento` value is `{ isTrusted: false }` and not a number tho.

![Screenshot 2022-06-20 at 12 43 16](https://user-images.githubusercontent.com/14028029/174585673-a5e61588-bc4b-4213-ad44-31a04cdba33a.png)

Additionally, you could just use the `useLocalStorage` hook like an `useState` hook and read this value in your component. The `useReadLocalStorage` is made to listen the value from another component. 

Good luck 😉
