### ISSUE TITLE
Linting errors for useCopyToClipboard

### ISSUE THREAD

**Issue by boazpoolman** [juliencrn/usehooks-ts#178]
Maby I'm doing something wrong, but I'm getting `unsafe` linting errors when using the useCopyToClipboard hook.
![Schermafbeelding 2022-07-05 om 12 44 05](https://user-images.githubusercontent.com/9551934/177311042-919602b0-81d9-425b-9ca8-1b4f31335465.png)

**Comment by mrdulin** [comment]
Can you provide a codesandbox?

**Comment by joaquinmoreira** [comment]
I'm getting a violation of `no-unsafe-call` with `useOnClickOutside` as well

**Comment by juliencrn** [comment]
Hi! Thanks for the feedback. 

I added the recommended stricter  `@typescript-eslint` presets here #450 to prevent this kind of issue. It'll be released in the week.
I will close this issue due to both inactivity and missing bug reproduction. 
Feel free to re-open or create a new issue if the problem reappears.
