### ISSUE TITLE
Initialize windowSize state in useWindowSize to actual window dimensions

### ISSUE THREAD

**Issue by lewxdev** [juliencrn/usehooks-ts#212]
Small issue, but I've noticed that initializing the WindowSize to `{ width: 0, height: 0 }`
1. can cause some unpleasant UI/UX when using it for processing the layout and 
2. causes an unnecessary initial render

I understand using the `window` object without clear intentionality can cause issues with SSR,
but I'm curious if it's possible to use [the lazy initial state of `useState()`](https://reactjs.org/docs/hooks-reference.html#lazy-initial-state) to ensure `typeof window !== "undefined"`:

[Reference](https://github.com/juliencrn/usehooks-ts/blob/master/src/useWindowSize/useWindowSize.ts#L11) / Proposed update:
```ts
const [windowSize, setWindowSize] = useState<WindowSize>(() => ({
  width: window.innerWidth,
  height: window.innerHeight,
}))
```

**Comment by ro0t** [comment]
I second this. Getting weird results combining this with a custom useIsMobile hook when not listening to changes for good reasons.

**Comment by viveleroi** [comment]
Initial values being zero are breaking our use of react-resizable-panels. They only accept measurements in percentages so we have to use the window dimensions to convert pixel measurements for default/initial sizes into percentages. Because they use the first value received, and the initial dimensions from this hook are `0`, all sizes are 0.

For the time being I'm doing this but it seems like there's no reason not to fix set window.innerWidth etc as the first state values.

```
let { width } = useWindowSize()
width = width === 0 ? window.innerWidth : width
```

**Comment by juliencrn** [comment]
Hi, thanks for bug report. 
#451 and #472 should have been fixed this. 

In CSR (like using vite), it does initialize with the window size initially.
In SSR (like using Next), we can't initialize with a value because the first render is on the server, reading `window` in the `useState` initializer creates a hydration mismatch. In this case, you should pass `{ initializeWithValue: false }` and the hook will initially renders `{ width: undefined, height: undefined }`, then the real size will be hydrated in the `useEffect`. You can set default values on your side;

```ts
// SSR
const { width = 0, height = 0 } = useWindowSize({ initializeWithValue: false });
```

If you really need to have the window size straight, you should not use it in SSR context, using something like [`useIsClient`](https://usehooks-ts.com/react-hook/use-is-client) before
