### ISSUE TITLE
[Discussion] Would using useLayoutEffect in useDarkMode fix theme flickering?

### ISSUE THREAD

**Issue by zanzlender** [juliencrn/usehooks-ts#321]
I've seen many sites that use darkMode with React that have the problem where the theme flickers on load. The same thing happens on the usehooks-ts site for example.

That made me wonder... If using useDarkMode hook, would this issue be solved if instead of using the useLocalStorage hook, we call some type of function to retrieve the theme from storage, or from browser inside a useLayoutEffect hook? 

I know this would introduce some other problems, but could this be a doable solution?

**Comment by juliencrn** [comment]
The `useDarkMode` hook has been updated since the issue was created. I'll close the issue for inactivity, feel free to re-open if needed. 

About the theme flickering, in CSR applications like when using Vite, it works without flickering. However, you're right on SSR. IMHO we can't fix it using a hook because we can't read LocalStorage nor user preference on the server and so, we have to wait until the hydration, that's the source of flickering.
For the `usehooks-ts` website, I've removed the ThemeSwitch and only listen for `@media (prefers-color-scheme: dark) {}` in `.css`.

**Comment by zanzlender** [comment]
I already forgot about this issue 😅

With server actions lately I have been storing the theme in the db to automatically load the needed styles 👌
