### ISSUE TITLE
useEventListener logic is broken

### ISSUE THREAD

**Issue by mendrik** [juliencrn/usehooks-ts#56]
usually in the first cycle the element ref is null and even though a ref element is present it will attach a listener to the window object. If ref is given it should wait until ref.current is available before attaching any events

**Comment by juliencrn** [comment]
Hi @mendrik, good observation, but I think in this situation, we are done.

![1_552z6hbX_b648DjpTLHZNg](https://user-images.githubusercontent.com/14028029/140803345-49978c4e-afc0-4f8d-8e50-d1d0c82c51c0.png)

Like you can see in this image, the `ref` is set before the effect was triggered, so, in other word, when we are in the `useEffect` callback, the `ref` must be OK. 

You can make another test, create a component like this: 

```tsx
function Component() {
  const ref = useRef<null | HTMLDivElement>(null)

  useEffect(() => {
    console.log(ref)
  }, [])

  return <div ref={ref}>Example</div>
}
```

You can see in your console that in the only one console.log output, the ref is well-defined.

However, I can miss something, if you have an use-case with a issue, I'm open to re-check, any feedback is always welcome!

**Comment by mendrik** [comment]
hmm maybe I debugged something wrong then. I thought it had attached the listener to window object. closing

**Comment by schontz** [comment]
I think making the target an optional parameter is a recipe for errors. Consider the following:

```javascript
const LogClicks = forwardRef((props, ref) => {
  useEventListener('click', (e) => console.log(e.target), ref)
  return <div ref={ref}>{children}</div>
})

const UsesComponent = () => {
  return (<div><LogClicks>Hello</LogClicks></div>)
}
```

Since no ref is passed, it will remain `null`, and the click handler will be attached to the window. This is but one example of "what if the ref is not set?"

I believe it would be wiser to make the target required and never fallback to window, as it is easy to provide and prevents any confusion. This would also make the signature similar to the actual DOM method:

```javascript
// If there is no target, no op
useEventListener(target, 'eventName', callbackFn)

// Looks about like:
target.addEventListener('eventName', callbackFn)
```
